Buyer notification created
aws-samples/aws-marketplace-serverless-saas-integration pull request #23
Opened 2021-06-07 21:43 UTC by kumarpawan1

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-09 07:11 UTC, gjoshevski commented
What happens if the MarketplaceSellerEmail is not confirmed?

2021-06-11 15:00 UTC, chotafakir commented
Why is the test listing (WUPHF.com) and test email data hard-coded in the script "src/register-new-subscriber.js"? Will it be updated as an input parameter in the main template?

2021-06-11 15:05 UTC, chotafakir reviewed
The customer name and ISV name should be dynamic and pull the information from landing page submission data and product listing. The hard-coded email with dummy data will require editing the script before launching the stack, and that defeats the purpose of 1-click launch.

2021-06-15 18:14 UTC, gjoshevski requested changes

2021-06-15 18:14 UTC, gjoshevski commented on template.yaml
> +  MarketplaceSellerEmail:
This parameter should be optional. What if I want to use my own service for sending emails?

2021-06-15 18:14 UTC, gjoshevski commented on src/register-new-subscriber.js
> +       await setBuyerNotificationHandler(contactEmail);
This step should be performed only if MarketplaceSellerEmail is provided. MarketplaceSellerEmail should be optional.

2021-06-15 18:14 UTC, gjoshevski commented on README.md
> +* [Verify an email address](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses-procedure.html): This document gives step by step instructions to verify email address that wi
This does not feel like the right place to provide this link. All of the above links are AWS Marketplace related and intended to help the users understand AWS Marketplace. Please provide this instructions and explanation in the deployment section.

2021-06-15 18:14 UTC, gjoshevski commented on src/register-new-subscriber.js
> +  var params = {
to be consistent with the coding standard, please do not use var.

2021-06-15 18:14 UTC, gjoshevski commented on template.yaml
> +        - Statement:
Why is this overwriting the !If statment?

2021-07-30 09:03 UTC, gjoshevski approved these changes

2021-07-30 09:04 UTC, merged